# Generated by Django 5.0 on 2023-12-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
